# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Raf
tagline:          'Newb Software Engineer trying to pick up some slacks'
description:      'Here I write as often as I could about various topics, usually around Software Engineering. 
                   As an aspiring Wordsmith (did I use that correctly?), writing hopefully helps me to think and solve problems better, and help me to communicate more effectively.'
url:              http://mrafsyam.github.io
baseurl:          /

author:
  name:           'Raf'
  url:            https://twitter.com/mrafsyam

gems: [jekyll-paginate]
paginate: 30
paginate_path: "page:num"

# Custom vars
version:          1.0

github:
  repo: https://github.com/mrafsyam/mrafsyam.github.io.git
