# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Raf
tagline:          'Aspiring Software Engineer trying to pick up some slacks'
description:      'I scribble about this and that, usually Software Engineering. Aspiring to be a wordsmith (hope I got that right), writing helps me think, solve problems, and communicate better.'
url:              https://www.instagram.com/zeroquitgenes/
baseurl:          /

author:
  name:           'Raf'
  url:            https://twitter.com/mrafsyam

gems: [jekyll-paginate]
paginate: 500
paginate_path: "page:num"

# Custom vars
version:          1.0

github:
  repo: https://github.com/mrafsyam/mrafsyam.github.io.git
