# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Raf blog
tagline:          'Noob developer trying to pickup some slacks'
description:      'Here I write as often as possible about various topics, usually around software developement.'
url:              http://mrafsyam.github.io
baseurl:          /

author:
  name:           'Raf'
  url:            https://www.instagram.com/mrafsyam

gems: [jekyll-paginate]
paginate: 10
paginate_path: "page:num"

# Custom vars
version:          1.0

github:
  repo: https://github.com/mrafsyam/mrafsyam.github.io.git
