---           
layout: post
title: Jquery Mobile
date: 2011-11-17 18:55:12 UTC
updated: 2011-11-17 18:55:12 UTC
comments: false
categories: 
---

<table cellpadding="0" cellspacing="0" class="tr-caption-container" style="float: left; margin-right: 1em; text-align: left;"><tbody><tr><td style="text-align: center;"><a href="http://androinica.com/wp-content/uploads/2008/10/android_logo.png" imageanchor="1" style="clear: left; margin-bottom: 1em; margin-left: auto; margin-right: auto;"><img border="0" height="320" src="http://androinica.com/wp-content/uploads/2008/10/android_logo.png" width="320" /></a></td></tr><tr><td class="tr-caption" style="text-align: center;">Adroid, The open source Mobile OS. </td><td class="tr-caption" style="text-align: center;"><br /></td><td class="tr-caption" style="text-align: center;"><br /></td><td class="tr-caption" style="text-align: center;"><br /></td></tr></tbody></table>I asked a friend so that I can join in any project that involves some programming. Programming is a skill set that needs to be nurtured as always as possible, hence why. He introduced to me, sort of, the android developement stuff and I am pretty much, currently, hooked up to it. <br /><br />Pretty neat stuff. I never actually code Java before. Everything is new to me. This is going to be tough, and I'll just have to like it. I've been doing some readings and tried some examples. I'm not sure how I put it, but as far as I have discovered, there are tonnes of people out there who are very much experts in this field. When you feel like a newbie in any skills, you feel dismotivated. Thanks god that this is Malaysia. Not that many people are good in this stuff, just yet. But I could be wrong. Heck I think I'm wrong. But what the heck, this stuff are interesting, I must say.<br /><br />I applied for a part time job at the nearby petrol station and was accepted. My first day starts this Saturday. Currently, it's 3 days per week job, from 3pm - 11pm. Yes, it's 8 hours job. I'm not sure yet how much I'm making, but I really do hope that this will give me some motivation to take care of my valueable time each day of the week. And I do hope this will cover my living expenses.<br /><br />I end this with a quote: Chances are like playing poker. You will get a hand as soon as you fold.