---           
layout: post
title: Nasi Lemak buatan Bangi :D
date: 2011-10-11 13:30:54 UTC
updated: 2011-10-11 13:30:54 UTC
comments: false
categories: 
---

<table cellpadding="0" cellspacing="0" class="tr-caption-container" style="float: left; margin-right: 1em; text-align: left;"><tbody><tr><td style="text-align: center;"><a href="http://1.bp.blogspot.com/-3FA8bCiRrhM/TpRD1f8qL_I/AAAAAAAAAM0/7ZLyStc4cvM/s1600/nasi-lemak.jpg" imageanchor="1" style="clear: left; cssfloat: left; margin-bottom: 1em; margin-left: auto; margin-right: auto;"><img border="0" height="240" kca="true" src="http://1.bp.blogspot.com/-3FA8bCiRrhM/TpRD1f8qL_I/AAAAAAAAAM0/7ZLyStc4cvM/s320/nasi-lemak.jpg" width="320" /></a></td></tr><tr><td class="tr-caption" style="text-align: center;">Ini bukan saya buat. Saya buat lagi huru-hara, haha</td></tr></tbody></table><span style="font-family: Georgia, &quot;Times New Roman&quot;, serif; font-size: x-large;"><strong>Oh</strong></span> yeah it's the semester break and I pretty much have nothing else to do. I didn't go back to Kemaman this time. I thought I could stay here in Bangi for a while because practically I wasn't living here during the study weeks. I wasn't busy with anything in particular, just filling up my free time learning stuff I wanted to learn during the study weeks. Websites, land buying, home buying, small business, all those future shit. <br /><br />I promised to the princess that I'll make her Nasi Lemak and go picnic with her somewhere with it. I tried&nbsp;out on one of&nbsp;the recipe I found online and what can I say......I can cook! (self confident level is 120% at this moment). I just need to put less onion.....and use Tamarind Juice, not the Tamarind Paste all the way...<br /><br />Here is the recipe:<br /><strong>Bahan untuk nasi :-</strong><br />@ 2 cawan beras<br />@ 1 cawan santan n 1 cawan air( jun guna 1/2 cwn santan pekat n 1 1/2 cwn air) <br />@ 1 helai daun pandan - disimpul <br />@ 3 hirisan halia <br />@ secubit garam <br /><br /><strong>Bahan untuk sambal :-</strong> <br />* 6 sudu besar cili kering mesin <br />* 4 ulas bawang merah -ditumbuk <br />* 2 ulas bawang putih -ditumbuk <br />* 1 biji bawang besar -dihiris <br />* segenggam ikan bilis (dibasuh, separuh darinya ditumbuk) <br />* sedikit air asam jawa <br />* sedikit belacan<br />* garam n gula <br /><br /><strong>Bahan sampingan lain :- </strong><br />Ikan bilis goreng, telur rebus dan timun. <br /><br /><strong>Cara-cara</strong> <br />1.Campur semua bahan untuk nasi dan masak seperti nasi biasa. <br />2.Tumis bawang besar, masukkan bawang2 yg ditumbuk, cili mesin, belacan dan ikan bilis yg ditumbuk..hingga sedikit garing dan pecah minyak. <br />3.Masukkan air asam dan separuh lagi ikan bilis yg sudah dibersihkan tadi. <br />4.Masukkan garam n gula. Masak sehingga agak pekat. <br /><br />p/s : Princess, this is for you. Don't tell me I don't work on anything for you, ever! :P