---           
layout: post
title: Internship
date: 2013-04-01 18:28:41 UTC
updated: 2013-04-01 18:28:41 UTC
comments: false
categories: 
---

<p>I am now into my final year of engineering study. I admit, I'm lagging behind of most of my peers. However, I'm living my life as much as they do, feeling blessed despite all of the shortcomings. </p><p>I'm currently doing my internship at a small local company named Tri System Technology. It has been a month and a half....and I'm enjoying it :) I discovered myself as a person who dislikes being idle, so sometimes having no tasks to complete day-to-day bored me easily. However, most of the time I'm pretty occupied. I'm here with another guy from MMU who is also my friend, Alex. </p><p>The company mainly involved in supplying and installing ICT solutions to newly built buildings which are offered through tender contract, mostly from TNB, TM and JKR. Lately, they are now into bigger projects such as MRT and Matrade.</p><p>For now, me and Alex are involved in MRT projects. In this project, Tri System is a subcontractor of Apex Communication and Johnson Control in Electronic Access Card (EAC) installation. Simply put, Tri System as subcontractor, are the one to do all the works. Me and Alex have been to the Interface Meeting since the beginning and I am proud to say that we are quite heavily involved in this project. The Interface Meeting enlightened me on how these people manage between a number of parties to make progress in the project. I'm glad having the opportunity to learn how they conduct the meetings, scheduled the work progress and coordinated between them. It is pretty much like our engineering group assignment, but this is on a huge project. </p><p>Cable routing, door schedules, those are the term we learned so far. I can't wait for more. This has been quite a good experience for me. </p><p>Need to get some sleep. Later.</p>