---           
layout: post
title: Logging with GWT
date: 2016-09-23 08:33:20 UTC
updated: 2016-09-23 08:33:20 UTC
comments: false
categories: 
---

1. First, modify our module configuration file (<b>X</b>.gwt.xml) where <b>X</b> is the class which holds the EntryPoint of your application.<br /><br /><pre>&lt;inherits name="com.google.gwt.logging.Logging" /&gt;<br />&lt;set-property name="gwt.logging.logLevel" value="INFO"/&gt;<br />&lt;set-property name="gwt.logging.enabled" value="TRUE"/&gt;<br />&lt;set-property name="gwt.logging.consoleHandler" value="ENABLED"/&gt;<br />&lt;set-property name="gwt.logging.popupHandler" value="DISABLED" /&gt;&lt;!-- Disable PopupLogHandler --&gt;<br />&lt;set-property name="gwt.logging.simpleRemoteHandler" value="DISABLED" /&gt;</pre><br /><br />2. This configuration cause logs to be printed to standard output, that is usually Eclipse console window. You can also view this logs in Javascript console, which present in Chrome, Firefox and IE.<br /><br />See here on how to view them in Javascript console : <a href="http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers">http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers</a><br /><br /><br />3. In your class, import the library.<br /><br /><span style="font-family: &quot;courier new&quot; , &quot;courier&quot; , monospace;">import java.util.logging.Logger;</span><br /><span style="font-family: &quot;courier new&quot; , &quot;courier&quot; , monospace;">import java.util.logging.Level;</span><br /><br /><br />4. Then, instantiate the logger with whatever name, possibly with the class name to make it more descriptive.<br /><br /><span style="font-family: &quot;courier new&quot; , &quot;courier&quot; , monospace;">public Logger logger = Logger.getLogger("MyClassLogger");</span><br /><br /><br />5. Then it can be used anywhere within it's scope. Examples :<br /><br /><span style="font-family: &quot;courier new&quot; , &quot;courier&quot; , monospace;">logger.log(Level.SEVERE, "Connection refused: ");</span><br /><span style="font-family: &quot;courier new&quot; , &quot;courier&quot; , monospace;">logger.log(Level.INFO, "Query executed : " + executedQuery);</span><br /><br /><br />6. The log levels define the severity of a message. The Level class is used to define which messages should be written to the log. You can set the minimum level by the following :<br /><br /><span style="font-family: &quot;courier new&quot; , &quot;courier&quot; , monospace;">logger.setLevel(Level.INFO);&nbsp;</span><br /><br /><br />7. These are the typical usage of these levels :<br /><br /><b>ERROR</b>: Any error/exception that is or might be critical.<br /><br /><b>WARN</b>: Any message that might warn us of potential problems, e.g. when a user tried to log in with wrong credentials - which might indicate an attack if that happens often or in short periods of time<br /><br /><b>INFO</b>: Anything that we want to know when looking at the log files, e.g. when a scheduled job started/ended.<br /><br />