---           
layout: post
title: Setting up Java, Eclipse, MySQL and Tomcat in Windows for Java Web Developement
date: 2017-01-04 05:26:49 UTC
updated: 2017-01-04 05:26:49 UTC
comments: false
categories: 
---

1. Download Java Dev Kit (JDK, not JRE) from here : <a href="http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html">http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html</a><br />Important : write down the installation folder. This is your JAVA_HOME variable.<br /><br /><br />2. Set Envinronment Variables for Java.<br />Step 1 : Right Click on MyComputer and click on properties .<br />Step 2 : Click on Advanced tab<br />Step 3: Click on Environment Variables (bottom left)<br />Step 4: At User Variable section (top), create a few variables as below. You need to enter the Variable name and then the value:<br />&nbsp; &nbsp; JAVA_HOME : C:\Program Files\Java\jdk1.8.0_112 (put your actual Java installation)<br />&nbsp; &nbsp; JDK_HOME &nbsp;: %JAVA_HOME%<br />&nbsp; &nbsp; JRE_HOME &nbsp;: %JAVA_HOME%\jre<br />&nbsp; &nbsp; CLASSPATH : .;%JAVA_HOME%\lib;%JAVA_HOME%\jre\lib<br /><br />Step 5: At System Variable section (bottom), find a variable named PATH or path and at the end of the value with the following;<br /><br />for Windows 8 and below;<br />&nbsp; &nbsp;&nbsp;C:\Program Files\Java\jdk1.8.0_112\bin (your actual Java installation and within bin folder)<br />&nbsp; &nbsp; Note the the semicolon at the front of the path.<br /><br />or for Windows 10, click New and add the above path.<br /><br /><br />3. Check if everything is OK. Run command line tool (press Windows + x or use search for "cmd"). Run java -version and javac -version which should show the version.<br /><br /><br />4. Install Eclipse (use this Eclipse Java EE version) : <a href="http://www.eclipse.org/downloads/packages/eclipse-ide-java-ee-developers/neon2">http://www.eclipse.org/downloads/packages/eclipse-ide-java-ee-developers/neon2</a><br /><br /><br />5. Install Tomcat 8 : <a href="http://www-eu.apache.org/dist/tomcat/tomcat-8/v8.5.9/bin/apache-tomcat-8.5.9.exe">http://www-eu.apache.org/dist/tomcat/tomcat-8/v8.5.9/bin/apache-tomcat-8.5.9.exe</a><br />Note : Write down the installation folder, the webapps folder. You may bookmark or create shortcut of the folder on your Desktop.<br /><br />Tomcat should be running afterwards. You may browse to http://localhost:8080 to check that your Tomcat is installed fine.<br /><br /><br />6. Install MySQL server : <a href="https://dev.mysql.com/downloads/file/?id=467606">https://dev.mysql.com/downloads/file/?id=467606</a><br />Click on the "No thanks, just start my download."<br /><br />Once installed, run the MySQL installer. Select from the product list (click on&nbsp;+ sign) the MySQL server and then execute.<br /><br />Upon configuration, setup password for root and another user login (if you want). Rename the service name to MYSQL and set it to auto run at startup. You may want to create log files for each of the logs i.e. error, general and slow query logs.<br /><br /><br /><br />