---           
layout: post
title: User's crontab
date: 2017-02-16 07:01:27 UTC
updated: 2017-02-16 07:01:27 UTC
comments: false
categories: 
---

Per crontab man page:<br /><br />Each user can have their own crontab, and though these are files in /var/spool/cron/crontabs, they are not intended to be edited directly.<br /><br />Files under /var/spool are considered temporary/working and it's always a good practice to back up your cron entries or keep them in a file in your home directory.<br /><br />I assume you're using crontab -e to create crontab files on the fly. If so, you can get a "copy" of your crontab file by doing crontab -l. Pipe that to a file to get a "backup":<br /><br /><span style="font-family: &quot;courier new&quot; , &quot;courier&quot; , monospace;">crontab -l &gt; my-crontab</span><br /><br />Then you can edit that my-crontab file to add or modify entries, and then "install" it by giving it to crontab:<br /><br /><span style="font-family: &quot;courier new&quot; , &quot;courier&quot; , monospace;">crontab my-crontab</span><br /><br />This does the same syntax checking as crontab -e.<br /><br />To list all cron jobs from all users in your system:<br /><span style="font-family: &quot;courier new&quot; , &quot;courier&quot; , monospace;"><br /></span><span style="font-family: &quot;courier new&quot; , &quot;courier&quot; , monospace;">for user in $(cut -f1 -d: /etc/passwd)</span><br /><span style="font-family: &quot;courier new&quot; , &quot;courier&quot; , monospace;">do</span><br /><span style="font-family: &quot;courier new&quot; , &quot;courier&quot; , monospace;">&nbsp; echo $user</span><br /><span style="font-family: &quot;courier new&quot; , &quot;courier&quot; , monospace;">&nbsp; crontab -u $user -l</span><br /><span style="font-family: &quot;courier new&quot; , &quot;courier&quot; , monospace;">done</span><br /><span style="font-family: &quot;courier new&quot; , &quot;courier&quot; , monospace;"><br /></span>or<br /><span style="font-family: &quot;courier new&quot; , &quot;courier&quot; , monospace;"><br /></span><span style="font-family: &quot;courier new&quot; , &quot;courier&quot; , monospace;">for user in $(cut -f1 -d: /etc/passwd)</span><br /><span style="font-family: &quot;courier new&quot; , &quot;courier&quot; , monospace;">do</span><br /><span style="font-family: &quot;courier new&quot; , &quot;courier&quot; , monospace;">&nbsp; echo $user</span><br /><span style="font-family: &quot;courier new&quot; , &quot;courier&quot; , monospace;">&nbsp; crontab -l&nbsp;</span><span style="font-family: &quot;courier new&quot;, courier, monospace;">$user</span><span style="font-family: &quot;courier new&quot;, courier, monospace;">&nbsp;</span><br /><span style="font-family: &quot;courier new&quot; , &quot;courier&quot; , monospace;"></span><br /><span style="font-family: &quot;courier new&quot; , &quot;courier&quot; , monospace;">done</span>